# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jungsu Han
title: Backend Developer
email: saw1515@postech.ac.kr
website: www.github.com/jshan94

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jshan94


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a M.S. student advised by James Wonki Hong at the Department of Computer Science and Engineering, Pohang University of Science and Technology, Korea.
  My reasearch interests lie in <mark>Machine Learning</mark> and <mark>Blockchain</mark>.<br/>
  I'm also backend developer with business mind. 🚀 

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left # or top-middle
        title: CryptoQuant
        link: https://cryptoquant.com/overview/btc-exchange-flows
        sub_title: Software Developer
        caption: 2019.7 - 2020.1 (7 month)
        quote: >
          Actionable on-chain data, charts, alerts for investors in $BTC, $ETH, #Stablecoins
        description: | # this will include new lines to allow paragraphs
            * Analysis & Manufacture ETH & ERC-20 Stable coins on-chain data (about > 4TB)
            * Migrate DB server (MySQL to PostgreSQL)
            * Develop data query API for Quant service
            * Learn overall Blockchain industry & technology


  - title: Education # Title for the section
  
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: POSTECH
        caption: 2013.3 - 2019.8
        sub_title: MS Computer Science
        description: | # this will include new lines to allow paragraphs
          * Distributed Processing & Network Management (DPNM) Lab
          * GPA *3.92/4.3* 
              
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: POSTECH
        caption: 2013.3 - 2019.8
        sub_title: BS Computer Science
        description: | # this will include new lines to allow paragraphs
          * Internship 
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
            - title: Education # Title for the section
    
    


#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

##infos 
# Recipient of the POSTECH Alchemist Fellowship 2021.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
