# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jungsu Han
title: Backend Developer
email: saw1515@postech.ac.kr
website: www.github.com/jshan94

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jshan94


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a M.S. student advised by James Wonki Hong at the Dept. of CSE, POSTCH, Korea. <br/>
  My reasearch interests lie in <mark>Machine Learning</mark> and <mark>Blockchain</mark>. <br/>
  I'm also backend developer with business mind. 🚀 <br/>
  Love to work in a place where I can grow actively and quickly.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left # or top-middle
        title: CryptoQuant
        link: https://cryptoquant.com/overview/btc-exchange-flows
        sub_title: Backend Developer
        caption: 2019.7 - 2020.1 (7 month)
        quote: >
          Actionable on-chain data, charts, alerts for investors in $BTC, $ETH, #Stablecoins.
          Pre-A Quant service startup
        description: | # this will include new lines to allow paragraphs
            * Analysis & Manufacture ETH & ERC-20 Stable coins on-chain data (about > 4TB)
            * Migrate DB server (MySQL to PostgreSQL)
            * Develop data query API for Quant service
            * Learn overall Blockchain industry & technology

  - title: Projects
    layout: text
    content: | # this will include new lines to allow paragraphs
      - layout: top-middle
        name: CBDC system using Blockchain
        link: 
        quote: >
          2021.1 ~ 2021.11
        description: | # this will include new lines to allow paragraphs
          * CBDC (Central Bank Digital Currency) system using Blockchain
          * Collaboration with Hana Bank, [Demo](https://www.youtube.com/watch?v=DqvWH7rcHTU&ab_channel=POSTECHCCBR) 
          * Related Papers : [Cos-CBDC: Design and Implementation of CBDC on Cosmos Blockchain](https://ieeexplore.ieee.org/abstract/document/9562672)
          
      - layout: top-middle
        name: MyMu
        link: 
        quote: >
          2021.1 ~ 2021.3
        description: | # this will include new lines to allow paragraphs
          * Music Opensource Community Service [Pitching](https://youtu.be/yk07lsq_O7o)
          * **Excellent Award** in [2020 I-CORP](https://www.kitscenter.or.kr/home/main.do), **Encouragement Award** in [FESTA](https://m.yeongnam.com/view.php?key=20210130010003979)

  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: POSTECH
        caption: 2013.3 - 2019.8
        sub_title: MS Computer Science Engineering
        description: | # this will include new lines to allow paragraphs
          * Distributed Processing & Network Management (DPNM) Lab
          * Mainly studied about blockchain technology
          * Recipient of the POSTECH Alchemist Fellowship 2021 ($ 9,000)
          * *GPA 3.92/4.3* 

      - layout: left
        title: POSTECH
        caption: 2013.3 - 2019.8
        sub_title: BS Computer Science Engineering
        quote: >
          I didn't adjust well when I was a freshman, but after I was discharged from the military, I tried to have a variety of experiences.<br/>
          I have regrets for neglecting my studies, but that's why I want to work harder now.
        description: | # this will include new lines to allow paragraphs
          * 2013 ~ : Got academic probation 2 times in freshman due to my low grade
          * 2014 ~ : Enlisted in the army 
          * 2016 ~ : Studied hard (got scholarship in 2018) and Internship ([SK C&C](https://www.skcc.co.kr/),  [Netmarble](https://www.netmarble.net/),  [EXEM](https://ex-em.com/),  [Fitogether](https://www.fitogether.com/)) 
          * *GPA 2.82/4.3*
          
    - title: Skills # Title for the section
      - layout: left
        name: Backend
        description: | # this will include new lines to allow paragraphs
          * Language : NodeJS, Python
          * Framework : Linux, AWS, Firebase
      - layout: left
        name: Frontend
        description: | # this will include new lines to allow paragraphs
          * Language : Javascript (React)
      - layout: left
        name: Blockchain
        description: | # this will include new lines to allow paragraphs
          * Language : Solidity, Go
          * Framework : Remix, Blockchain Platforms(usually Ethereum, Cosmos)
          
#       - layout: left
#         name: Alogrithm or ML
#         description: | # this will include new lines to allow paragraphs
#           * ES6
#           * Npm, Grunt, Webpack
#           * Handlebars, Lodash
    
    
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
