# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jungsu Han
title: Backend Developer & Blockchain Researcher
email: saw1515@postech.ac.kr
website: www.github.com/jshan94

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jshan94
linkedin_username: jungsu-han-9596a113a


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm blockchain developer with business mind. 🚀 <br/>
  My reasearch interests lie in <mark>Cryptocurrencies</mark> and <mark>DeFi</mark>. <br/>
  Love to work in a place where I can grow actively and quickly.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout : left
        title : Terra
        link : https://www.terra.money/
        sub_title: Core Engineering
        caption : 2022.04 - Current
        quote : >
          Terra is a blockchain protocol and payment platform used for algorithmic stablecoins.
          
        description : |
          * Maintain SDK (Python and Javascript) for Terra mainnet 
          * Develop smartcontract with CosmWasm 
          * Develop terra 1.0 and 2.0 mainnet

      - layout : left
        title : GPEX
        link : https://gpex.io/kr/
        sub_title: Blockchain Developer
        caption : 2022.01 - 2022.03 (3 month)
        quote : >
          GPEX, the high-speed platform moving illiquid brand points to highly liquid markets.
          
        description : |
          * Setup GPEX network with [polygon-edge](https://github.com/0xPolygon/polygon-edge)
          * Setup basic infra for GPEX ecosystem (Explorer with blockscout, Stats monitor with eth-stats)
          * Setup bridge for interoperability with ethereum  

      - layout: left # or top-middle
        title: CryptoQuant
        link: https://cryptoquant.com/overview/btc-exchange-flows
        sub_title: Backend Developer
        caption: 2019.07 - 2020.01 (7 month)
        quote: >
          Quant service startup for Blockchain investing. <br/>
          Actionable on-chain data, charts, alerts for investors in $BTC, $ETH, $Stablecoins.
          
        description: | # this will include new lines to allow paragraphs
          * Analysis & Manufacture ETH & ERC-20 Stable coins on-chain data (about > 4TB)
          * Migrate DB server (Elastic Search to RDB)
          * Develop data query API for Quant service
          * Learn overall Blockchain industry & technology

  - title: Projects
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: FastCampus Blockchain Lecture
        caption: 2022.08 ~ 2022.11
        description: | # this will include new lines to allow paragraphs
          * FastCampus is the most popular online education platform for adults in korea
          * Lecture topic - Wallet, Bridge, Block Explorer etc. 
          * About 40 classes for 13 hours
          * [Class Link](https://fastcampus.co.kr/dev_online_blockchain)
      - layout: left
        title: Blockchain-based CBDC 
        caption: 2021.1 ~ 2021.11
        description: | # this will include new lines to allow paragraphs
          * CBDC (Central Bank Digital Currency) system using Blockchain
          * Collaboration with Hana Bank ([Demo](https://www.youtube.com/watch?v=DqvWH7rcHTU&ab_channel=POSTECHCCBR)) 
          * Related Papers : [Cos-CBDC: Design and Implementation of CBDC on Cosmos Blockchain](https://ieeexplore.ieee.org/abstract/document/9562672)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: POSTECH
        caption: 2020.3 - 2022.2
        sub_title: MS Computer Science Engineering
        quote: >
          Studied the latest blockchain industry and technical background. Interested in Defi and Cryptocurrencies.
        description: | # this will include new lines to allow paragraphs
          * Distributed Processing & Network Management ([DPNM](http://dpnm.postech.ac.kr/)) Lab
          * MS Thesis : [Design and Implementation of Central Bank Digital Currency using Blockchain](http://dpnm.postech.ac.kr/thesis/22/Jungsoo_thesis.pdf)
          * Recipient of the POSTECH Alchemist Fellowship 2021 ($ 10,000)
          * *GPA 3.92/4.3* 
      - layout: left
        title: POSTECH
        caption: 2013.3 - 2019.8
        sub_title: BS Computer Science Engineering
        description: | # this will include new lines to allow paragraphs
          * 2013 ~ : Got academic probation 2 times in freshman due to my low grade
          * 2014 ~ : Enlisted in the army 
          * 2016 ~ : Got scholarship in 2018 and Complete internship programs ([SK C&C](https://www.skcc.co.kr/),  [Netmarble](https://www.netmarble.net/),  [EXEM](https://ex-em.com/),  [Fitogether](https://www.fitogether.com/)) 
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          * Language : TypeScript, Python
          * Framework : Linux, AWS
      - layout: left
        title: Blockchain
        description: | # this will include new lines to allow paragraphs
          * Language : Solidity, Go, Rust
          * Framework : Ethereum, Cosmos-SDK, CosmWasm
      
      
    
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
