# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jungsu Han
title: Backend Developer
email: saw1515@postech.ac.kr
website: www.github.com/jshan94

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jshan94


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a M.S. student advised by James Wonki Hong at the Department of Computer Science and Engineering, Pohang University of Science and Technology, Korea.
  My reasearch interests lie in <mark>Machine Learning</mark> and <mark>Blockchain</mark>.<br/>
  I'm also backend developer with business mind. 🚀 

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left # or top-middle
        title: CryptoQuant
        link: https://cryptoquant.com/overview/btc-exchange-flows
        sub_title: Software Developer
        caption: 2019.7 - 2020.1 (7 month)
        quote: >
          Actionable on-chain data, charts, alerts for investors in $BTC, $ETH, #Stablecoins.
          Pre-A Quant service startup
        description: | # this will include new lines to allow paragraphs
            * Analysis & Manufacture ETH & ERC-20 Stable coins on-chain data (about > 4TB)
            * Migrate DB server (MySQL to PostgreSQL)
            * Develop data query API for Quant service
            * Learn overall Blockchain industry & technology


  - title: Education # Title for the section
  
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: POSTECH
        caption: 2013.3 - 2019.8
        sub_title: MS Computer Science
        description: | # this will include new lines to allow paragraphs
          * Distributed Processing & Network Management (DPNM) Lab
          * Mainly studied about blockchain technology
          * POSTECH alchemist fellowship ($ 9,000)
          * *GPA 3.92/4.3* 
              
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: POSTECH
        caption: 2013.3 - 2019.8
        sub_title: BS Computer Science
        quote: >
          I didn't adjust well when I was a freshman, but after I was discharged from the military, I tried to have a variety of experiences.<br/>
          I have regrets for neglecting my studies, but that's why I want to work harder now.
        description: | # this will include new lines to allow paragraphs
          * 2013 ~ : Got academic probation 2 times in freshman due to my low grade
          * 2014 ~ : Enlisted in the army 
          * 2016 ~ : Studied hard (got scholarship in 2018) and Did internship in many companies every vacation ([SK C&C](https://www.skcc.co.kr/),  [Netmarble](https://www.netmarble.net/),  [EXEM](https://ex-em.com/),  [Fitogether](https://www.fitogether.com/)) 
          * *GPA 2.82/4.3* 
    
    


#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

##infos 
# Recipient of the POSTECH Alchemist Fellowship 2021.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
