# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jungsu Han (Harvey)
title: On-chain Analytics & Ecosystem Support
email: saw151515@gmail.com
website: www.github.com/jshan94

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jshan94
linkedin_username: jungsu-han-9596a113a


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Driving growth in Web3 through on-chain analytics, partnerships, and community engagement. <br/>
  Passionate about connecting blockchain technology with real users and building sustainable communities.<br/>
  <ul>
    <li>B.S. & M.S. in Computer Science (POSTECH)</li>
    <li>Experience in blockchain core engineering and developer relations</li>
    <li>Focused on growth, partnerships, and marketing across Korea regions</li>
  </ul>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout : left
        title : Initia Labs
        link : https://initia.xyz/
        sub_title: Core Engineer & DevRel
        caption : 2023.01 - Current
        quote : >
          Initia is a unified L1+L2 blockchain protocol that lets developers easily build custom rollups

        description : |
          * Worked as DevRel & Ecosystem Growth
            * Led third-party onboarding, providing technical guidance and managing partnerships
            * Produced technical and community-facing content (research articles, talks) to educate and grow the ecosystem ([Mammothon](https://mammothon.celestia.org/))
            * Organized community events, delivered presentations, and hosted developer sessions ([ETHCC 2024](https://ethcc.io/))
            * Authored comprehensive [documentation](https://docs.initia.xyz/) and tutorials to accelerate developer adoption and user growth
          * Worked as Core Engineer
            * Contributed to the core development of the Initia blockchain protocol: [Initia MoveVM](https://github.com/initia-labs/movevm), [Initia Client](http://github.com/initia-labs/initia)
            * Designed and implemented the [VIP contract](https://github.com/initia-labs/vip-contract) and supporting indexer, APIs, and bots
            * Implemented the first version of OPinit bots for the Initia Optimistic bridging stack
            * Built developer tools for seamless integration with Initia chains, including [initia.js](https://github.com/initia-labs/initia.js) and [initia-registry](github.com/initia-labs/initia-registry)
          
      - layout : left
        title : Terra
        link : https://www.terra.money/
        sub_title: Core Engineering
        caption : 2022.04 - 2023.01
        quote : >
          Terra is a blockchain protocol and payment platform used for algorithmic stablecoins.
          
        description : |
          * Proficient in Cosmos SDK architecture, with hands-on experience in modules like staking, bank, and auth
          * Developed and deployed smart contracts using CosmWasm
          * Proposed and prototyped a novel storage fee mechanism
          * Maintained and optimized ETL SDKs (Python and JavaScript) for Terra Mainnet analytics
          * Participated in the migration process from Terra Classic to Terra 2.0
        
      - layout: left # or top-middle
        title: CryptoQuant
        link: https://cryptoquant.com/overview/btc-exchange-flows
        sub_title: Backend Developer
        caption: 2019.07 - 2020.01 (7 month)
        quote: >
          Quant service startup for Blockchain investing. <br/>
          Actionable on-chain data, charts, alerts for investors in $BTC, $ETH, $Stablecoins.
          
        description: | # this will include new lines to allow paragraphs
          * Engineered backend systems for large-scale analysis of Ethereum and ERC-20 stablecoin on-chain data (> 4TB)
          * Led migration of backend infrastructure from Elasticsearch to a relational database system
          * Developed robust API services powering real-time quant tools and data visualization dashboards
          * Acquired broad technical and market knowledge of the blockchain and crypto analytics industry

  - title: Projects
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: Hackathon
        description: |
         * [2025 Hyperliquid Hackathon Seoul - Prize Winner](https://luma.com/5wzngdgk?tk=HLeiBN)
         * [2024 ETHseoul 1st Prize (Celo Track)](https://ethseoul2024.devfolio.co/projects?prizes=38a8ac53a601405494592ce3ac82f41b&show_winners=true)
      - layout: left
        title: CURG (Crypto Users Research Group)
        caption: 2024.03 ~
        description: |
          * CURG is Korea-based developer community of blockchain engineers and builders
          * Contributed to the ecosystem through open-source projects, research, and collaborative building
          * Organized seminars, meetups, and guest speaker sessions to promote blockchain adoption
          * Hosted academic–industry networking events, engaging students, developers, and startup founders
          * Served as a core organizer, managing community operations and coordinating initiatives
      - layout: left
        title: FastCampus Blockchain Lecture
        caption: 2022.08 ~ 2022.11
        description: | # this will include new lines to allow paragraphs
          * FastCampus is the most popular online education platform for adults in korea
          * Lecture topic - Wallet, Bridge, Block Explorer etc. 
          * About 40 classes for 13 hours
          * [Class Link](https://fastcampus.co.kr/dev_online_blockchain)
      - layout: left
        title: Blockchain-based CBDC 
        caption: 2021.1 ~ 2021.11
        description: |
          * CBDC (Central Bank Digital Currency) system using Blockchain
          * Collaboration with Hana Bank ([Demo](https://www.youtube.com/watch?v=DqvWH7rcHTU&ab_channel=POSTECHCCBR)) 
          * Related Papers : [Cos-CBDC: Design and Implementation of CBDC on Cosmos Blockchain](https://ieeexplore.ieee.org/abstract/document/9562672)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: POSTECH
        caption: 2020.3 - 2022.2
        sub_title: MS Computer Science Engineering
        quote: >
          Studied the latest blockchain industry and technical background. Interested in Defi and Cryptocurrencies.
        description: | # this will include new lines to allow paragraphs
          * Distributed Processing & Network Management ([DPNM](http://dpnm.postech.ac.kr/)) Lab
          * MS Thesis : [Design and Implementation of Central Bank Digital Currency using Blockchain](http://dpnm.postech.ac.kr/thesis/22/Jungsoo_thesis.pdf)
          * Recipient of the POSTECH Alchemist Fellowship 2021 ($ 10,000)
          * *GPA 3.92/4.3* 
      - layout: left
        title: POSTECH
        caption: 2013.3 - 2019.8
        sub_title: BS Computer Science Engineering
        description: | # this will include new lines to allow paragraphs
          * 2014 ~ : Enlisted in the army 
          * 2016 ~ : Got scholarship in 2018 and Complete internship programs ([SK C&C](https://www.skcc.co.kr/),  [Netmarble](https://www.netmarble.net/),  [EXEM](https://ex-em.com/),  [Fitogether](https://www.fitogether.com/)) 
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Languages
        description: |
          * Korean: Native
          * English: Business proficiency
          * Japanese: Business proficiency
    
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
